Feature/see profile frontend #t034
Nachodlv/elephant pull request #18
Opened 2020-09-06 00:24 UTC by NumaLeone

2020-09-08 13:14 UTC, Giansco submitted a review, later dismissed

2020-09-08 13:14 UTC, Giansco commented on front/elephant/src/app/components/see-profile/see-profile.component.html
> +      Guardar
Cambiar a "Editar"

2020-09-08 13:14 UTC, Giansco commented on front/elephant/src/app/components/see-profile/see-profile.component.html
> +      Cambiar contrasena
contraseña

2020-09-08 13:14 UTC, Giansco commented on front/elephant/src/app/components/see-profile/see-profile.component.html
> +      <mat-grid-tile>
Juntar Nombre y Apellido en un solo input. (Antes de mandarlo al back lo separas, de la misma forma que el register - consultame cualquier duda).

2020-09-08 13:14 UTC, Giansco commented on front/elephant/src/app/components/see-profile/see-profile.component.html
> +
Mostrar email de usuario como un texto, no como un input disabled (xq nunca lo vas a poder editar)

2020-09-09 13:07 UTC, Nachodlv requested changes

2020-09-09 13:07 UTC, Nachodlv commented on front/elephant/src/app/components/see-profile/see-profile.component.scss
> +  color: red;
Utilizar la variable red del archivo _vars.scss

2020-09-09 13:07 UTC, Nachodlv commented on front/elephant/src/app/components/see-profile/see-profile.component.html
> +<div class="div-container">
Los botones de "Cambiar contraseña" y "Eliminar usuario" deberían estar uno arriba del otro
![image](https://user-images.githubusercontent.com/22358277/92601897-bfc1ad00-f283-11ea-83d5-24fb6a78fa2f.png)

2020-09-09 13:17 UTC, Nachodlv approved these changes

2020-09-14 00:19 UTC, Nachodlv requested changes

2020-09-14 00:19 UTC, Nachodlv commented on front/elephant/src/app/components/see-profile/see-profile.component.html
> +<div class="div-container">
Continua sin respetar el wireframe

2020-09-15 12:48 UTC, Nachodlv requested changes

2020-09-15 12:48 UTC, Nachodlv commented on back/src/main/java/com/lab/elephant/security/SecurityConstants.java
> -  public static final String LOGOUT_URL = "/logout";
El backend no compila. Uno de los motivos es porque no encuentra esta URL

2020-09-15 12:48 UTC, Nachodlv commented on front/elephant/src/app/components/see-profile/see-profile.component.ts
> +export class SeeProfileComponent implements OnInit {
El frontend no compila. El componente no se encuentra en app.module.ts

2020-09-16 18:16 UTC, Nachodlv approved these changes

2020-09-16 18:18 UTC, merged