Feature/add comment integration t#047
Nachodlv/elephant pull request #40
Opened 2020-09-27 01:19 UTC by NumaLeone

2020-10-06 15:47 UTC, Nachodlv submitted a review, later dismissed

2020-10-06 15:47 UTC, Nachodlv commented on front/elephant/src/app/services/comment.service.ts
> +  createComment(idNote, comment: Comment): Observable<any> {
Debería retornar un ```Observable<Note>```

2020-10-06 15:47 UTC, Nachodlv commented on front/elephant/src/app/components/comment/comment.component.ts
> +        this.snackBar.openSnackbar('¡Creación de Comentario Exitoso!', 0);
Una vez creado el comentario se debería poder ver en la lista de comentarios.

2020-10-08 23:20 UTC, Dwape requested changes
Se tienen que cambiar dos cosas:
- Hacer que el refresh se haga solo si el comentario se crea exitosamente.
- Agregar un mensaje de error si falla la creación de comentario en el backend (Cuando se hace el `subscribe` después de llamar a la función `createComment()` se puede mandar un segundo argumento para el manejo del caso de error).

2020-10-08 23:20 UTC, Dwape commented on front/elephant/src/app/components/comment/comment.component.ts
> +    window.location.reload();
En lugar de hacer el refresh cuando se hace click sobre el botón, es mejor que se haga el refresh una vez que se recibe la respuesta del back. De esta forma si hay un error no se hace el refresh y si no hay errores nos podemos asegurar de que después del refresh el nuevo comentario va a estar en la lista de comentarios que devuelve el back (hacerlo así es lo mas parecido a la forma "correcta" de hacerlo, que dijimos de no hacer, en la que una vez que el back confirma que se agregó correctamente la nota, la agregamos en la lista de notas sin hacer un refresh).

2020-10-12 16:32 UTC, Dwape requested changes

2020-10-12 16:32 UTC, Dwape commented on front/elephant/src/app/components/comment/comment.component.ts
>        });
Es importante que si la creación del comentario falla, se muestre un mensaje de error. Para hacer eso, hay que pasarle como segundo parámetro al `subscribe` una función para ejecutar en caso de error:
```
this.commentService.createComment(this.noteId, newComment).subscribe(res => {
    this.snackBar.openSnackbar('¡Creación de Comentario Exitoso!', 0);
    this.refresh();
}, error => {
    this.snackBar.openSnackbar('No se ha podido crear el comentario. Intentelo nuevamente.', 0);
});
```

2020-10-13 20:38 UTC, Dwape approved these changes

2020-10-13 20:38 UTC, merged