made the logout frontend and added snackbar when user signs out
Nachodlv/elephant pull request #43
Opened 2020-10-01 18:01 UTC by NumaLeone

2020-10-01 21:27 UTC, Nachodlv requested changes

2020-10-01 21:27 UTC, Nachodlv commented on front/elephant/src/app/components/navbar/navbar.component.ts
> +    this.router.navigate(['']);
Cambiar esta linea para que el snackbar se abre una vez que se termine de redirigir a la pagina de login.
```
this.router.navigate(['']).then(() => this.snackbar.openSnackbar('Usted ha cerrado sesión correctamente!'));
```

2020-10-01 21:28 UTC, Nachodlv requested changes

2020-10-01 21:28 UTC, Nachodlv commented on front/elephant/src/app/components/navbar/navbar.component.html
> +    <button mat-menu-item (click)="logout()">Cerrar sesión</button>
No mostrar en caso que no este logeado

2020-10-09 00:37 UTC, Dwape requested changes
Cuando se cierra sesión hay que hacer una request al backend. La ruta para cerrar sesión es `logout` (con método `POST`). Si la request falla, se debe mostrar un mensaje de error al usuario.

2020-10-12 16:42 UTC, Dwape commented
Hay que ser consistente con el nombre de las branches. El titulo de la PR es `feature/log-out-frontend-T#010` pero la branch es `feature/log-out-T#010`. Esto no necesariamente sería un problema si la branch `feature/log-out-frontend-T#010` no existiera, pero existe. Igual tiene que estar claro cuál es la tarea y no puede haber confusión en el nombre de la branch.

2020-10-12 16:50 UTC, Dwape requested changes

2020-10-12 16:50 UTC, Dwape commented on front/elephant/src/app/components/navbar/navbar.component.ts
> +    this.userService.logout().subscribe(res => {
Tiene el mismo problema que la tarea de agregar comentario. Si hay un error, no se muestra el mensaje de error.

2020-10-13 21:27 UTC, Dwape approved these changes

2020-10-13 21:27 UTC, merged