Feature/create note frontend #t013
Nachodlv/elephant pull request #8
Opened 2020-08-25 19:45 UTC by NumaLeone

2020-08-26 23:04 UTC, Giansco commented on front/elephant/src/app/components/navbar/navbar.component.html
> +    <button mat-menu-item (click) = resgisterUser()>Regisrarse</button>
Para ser consistentes, siempre ponemos el '=' pegado a los parentesis y el cuerpo entre comillas dobles.
(click)="registerUser()"

Typo en "resgisterUser". Presta atención a las sugerencias del IDEA, que te marca el error ortografico.

2020-08-26 23:08 UTC, Giansco commented on front/elephant/src/app/components/navbar/navbar.component.ts
> +  // tslint:disable-next-line:typedef
Hay muy pocos casos en los que es aceptable ignorar tslint. En este caso no era necesario, simplemente agregale el tipo que devuelve al metodo
resgisterUser(): void {...}

2020-08-26 23:13 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.html
> +  <div><mat-icon class="plus-create">add</mat-icon></div>
No se puede definir un div dentro de un button, deberias usar una card clickeable.

2020-08-26 23:17 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.html
> +<button class="create-button" routerLink="/note/create">
La idea era que lo de crear nota este dentro de un modal, por eso en el wireframe tiene una cruz para cerrarlo. Es bastante sencillo pasarlo a un modal, no tenes que hacer todo devuelta, si necesitas ayuda avisa.

2020-08-26 23:29 UTC, Giansco commented on front/elephant/src/app/components/home/home.component.scss
> +  background-color:#cccccc;
Esto no deberia definirse en home.component, tiene mas sentido que este en styles.scss. Ademas, me parece que no esta teniendo ningún efecto.
Tambien tene en cuenta que existe el archivo _vars.scss que define la paleta de colores. El color #cccccc deberias agregarlo a la paleta e importarlo donde quieras usarlo.

2020-08-26 23:32 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.html
> +    <p class="close-button" mat-button routerLink="/home"><mat-icon>close</mat-icon>
El 'p' no puede estar dentro del span.
'p' no admite el atributo mat-button.

2020-08-26 23:36 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.html
>      <br>
Los dos br no hacen nada. No deberias usar el tag br de esta forma, para eso estan los margenes y paddings

2020-08-26 23:40 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.scss
> +  background-color: #cccccc;
importar desde _vars.scss

2020-08-26 23:45 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.ts
>      console.log(this.noteForm.controls.title);
Deberias llamar al metodo createNote del note.service.ts y mostrar un mensaje de exito llamando a snackbar.service.ts

2020-08-26 23:47 UTC, Giansco commented on front/elephant/src/app/services/note.service.ts
> +import {catchError, map, tap} from 'rxjs/operators';
Import no usado, catchError

2020-08-26 23:47 UTC, Giansco commented on front/elephant/src/app/services/note.service.ts
> +
Borrar extra espacios

2020-08-26 23:50 UTC, Giansco commented on front/elephant/src/app/app-routing.module.ts
> +import {NoteCreatorComponent} from "./components/note-creator/note-creator.component";
Los imports deben ser con comillas simples

2020-08-26 23:53 UTC, Giansco commented on front/elephant/src/app/components/navbar/navbar.component.html
>      Elephant
El h1 tiene un efecto traslucido raro

2020-08-27 00:02 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.ts
>      console.log(this.noteForm.controls.title);
Falta el chequeo de caracteres maximos en titulo (60) y mostrar mensaje de error en caso de que lo supere.

2020-09-01 14:16 UTC, Giansco commented on front/elephant/src/app/services/note.service.ts
> -
Agegar espacio

2020-09-01 14:19 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.ts
> +  submitted = false;
eliminar variables no utilizadas

2020-09-01 14:19 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.ts
> +/*
eliminar código viejo

2020-09-01 14:20 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.scss
> +  background-color: #333333;
Importar colores de _vars.scss

2020-09-01 14:21 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.ts
Eliminar variable no utilizada submitted

2020-09-01 14:22 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.ts
>      console.log(this.noteForm.controls.title);
Esto todavia no fue resuelto

2020-09-01 14:25 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.html
> +    <label class="create-label">Nombre</label>
class "create-label" nunca es utilizada

2020-09-01 14:34 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.scss
>  .create-input{
Agregar un poco de espacio entre la label "Nombre" y el input. Tambien quedaria mejor que la label este alineada horizontalmente con el input (ver foto).
![WhatsApp Image 2020-09-01 at 11 33 09](https://user-images.githubusercontent.com/22374322/91864798-0e999200-ec47-11ea-80c6-ab5d5eb8c62e.jpeg)

2020-09-01 14:37 UTC, Giansco commented on front/elephant/src/app/components/navbar/navbar.component.html
>      Elephant
Sigue teniendo el efecto.
![image](https://user-images.githubusercontent.com/22374322/91865223-89fb4380-ec47-11ea-8283-1cde66a9dafc.png)

2020-09-01 14:59 UTC, NumaLeone commented on front/elephant/src/app/components/note/note.component.scss
> +  background-color: #333333;
me salta un error al importar los colores del vars, eso queria preguntar  hoy en la clase

2020-09-07 01:16 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.scss
>  .create-input{
Falto agregar un poco de espacio entre la label "Nombre" y el input

2020-09-07 01:32 UTC, Giansco requested changes

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.html
>    <form class="create-note-form" [formGroup]="noteForm" (ngSubmit)="createNote()">
Eliminar tab extra de toda la form. Es decir, que este igual de indexado que el h2.

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.scss
>  .create-input{
Falto agregar un poco de espacio entre la label "Nombre" y el input

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/app-routing.module.ts
>    {path: 'note', component: NoteComponent},
Agregar AuthGuard a /note y /note/create

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/components/home/home.component.scss
> +  background-color:grey;
No es buena practica modificar el html y el body desde el scss de un componente, siempre es mejor hacerlo en styles.scss.
Por otro lado, el color elegido rompe el resto de las vistas, por ejemplo login o register. Me parece que seria mejor ir por un background white o whitesmoke. Cualquier cosa pregunta por slack.
![image](https://user-images.githubusercontent.com/22374322/92340125-92141280-f08f-11ea-8241-71af76b33e69.png)

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/components/note-creator/note-creator.component.ts
>      /*note: Note = new Note(id,title);
Eliminar codigo viejo

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/components/note/note.component.ts
>    cardName: string;
Eliminar variable no utilizada

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/models/Note.ts
> -
Agregar line-break

2020-09-07 01:32 UTC, Giansco commented on front/elephant/src/app/services/note.service.ts
> +  getNote(id): Observable<Note> {
Agregar line-break

2020-09-08 00:30 UTC, Giansco approved these changes

2020-09-08 00:30 UTC, merged